# Generated by Django 4.2.7 on 2023-11-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socios_del_club',
            name='Año_nacimiento',
            field=models.DateField(verbose_name='Año_nacimiento'),
        ),
        migrations.AlterField(
            model_name='socios_del_club',
            name='Correo_Electronico',
            field=models.EmailField(max_length=254, verbose_name='Correo_Electronico'),
        ),
        migrations.AlterField(
            model_name='socios_del_club',
            name='Fecha_Incorporacion',
            field=models.DateField(verbose_name='Fecha_Incorporacion'),
        ),
        migrations.AlterField(
            model_name='socios_del_club',
            name='Nombre_Socio',
            field=models.CharField(max_length=50, verbose_name='Nombre_Socio'),
        ),
        migrations.AlterField(
            model_name='socios_del_club',
            name='Sexo',
            field=models.CharField(max_length=50, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='socios_del_club',
            name='Telefono',
            field=models.CharField(max_length=30, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='socios_del_club',
            name='estado',
            field=models.CharField(max_length=50, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='socios_del_club',
            name='observacion',
            field=models.CharField(max_length=200, verbose_name='observacion'),
        ),
    ]
