# Generated by Django 4.2.7 on 2023-11-28 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_alter_socios_del_club_año_nacimiento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socios_del_club',
            old_name='Año_nacimiento',
            new_name='Fecha_nacimiento',
        ),
    ]
